### ISSUE TITLE
[FEAT] Remove the `sqlalchemy<2` constraint

### ISSUE THREAD

**Issue by katie-lamb** [moj-analytical-services/splink#1906]
### Is your proposal related to a problem?

I'm a splink fan (thank you for all your work!) and would like to use splink (python 3.11, DuckDB backend), for record linkage in our project, the [Public Utility Data Liberaion project (PUDL)](https://github.com/catalyst-cooperative/pudl) but am having incompatability issues due to PUDL's dependency on `pandas>2` and `sqlalchemy>=2`, whereas in splink `sqlalchemy` is pinned to `>=1.4.0,<2.0.0`. I see that in the dependency file `optional = true` is set for `sqlalchemy`, however it doesn't seem to be optional during installation (or in the `poetry.lock` file). It would be great if this version restriction could be removed.

The note in your dependency file seems to indicate that the lack of sqlalchemy 2.0 support is due to the lack of support in older versions of pandas. I believe you need at least v2.0 of pandas to use sqlalchemy 2.0. Are there plans to bump up the version requirement for `sqlalchemy`?

### Describe the solution you'd like

Bump up the version requirement and allow for an upgraded version of `sqlalchemy`. 

### Describe alternatives you've considered

I couldn't find any blocking issues or discussions besides the comment in the dependencies file about compatibility with pandas.

**Comment by RobinL** [comment]
Thanks - good spot.  We should fix this.

I think maybe I saw @ThomasHepworth was looking at doing some work to improve the dependencies, but not sure this is related.

If you're using duckdb, I don't think you actually need sqlalchemy at all, so as a temporary fix, you might just want to do a manual (no dependency) install of splink `pip install splink --no-deps`.  Then at a minimum you'll want to install the packages listed in these lines:
https://github.com/moj-analytical-services/splink/blob/47f7d20655b8760603ff14b050327092e2e6cce3/pyproject.toml#L12-L19

I think for almost all of them you can just pip install the latest version, the exception may be sqlglot.

**Comment by zaneselvans** [comment]
This is in the context of a much larger data pipeline which does depend on SQLAlchemy explicitly so we do need to keep it installed. We're using `conda` to manage our environment, and in [splink's conda recipe](https://github.com/conda-forge/splink-feedstock/blob/main/recipe/meta.yaml) it seems like the `sqlalchemy<2` requirement becomes [a hard constraint](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained):

```yaml
requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - jsonschema >=3.2,<5.0
    - python-duckdb >=0.8.0
    - pandas >=1.2.0
    - sqlglot >=7.0.0
    - altair >=5.0.1,<6.0
    - jinja2 >=3.0.3,<4.0.0
  run_constrained:
    - pyspark >=3.2.1
    - sqlalchemy >=1.4.0,<2.0.0
 ```

If the conflict with `pandas<2` is the only issue, might it make sense to remove the sqlalchemy version constraint in splink's dependencies and let users pin their own dependencies if they need to stay on pandas 1.x?

Related to this issue: https://github.com/catalyst-cooperative/pudl/pull/3302
